drone_inventory/__init__.py
from flask import Flask
from config import Config
from .api.routes import api
from .site.routes import site
from .authentication.routes import auth
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

from models import db as root_db, login_manager, ma

# Import for Flask-Marshmallow
from flask_marshmallow import Marshmallow

from flask_cors import CORS

from helpers import JSONEncoder

app = Flask(__name__)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)
app.config.from_object(Config)

root_db.init_app(app)

migrate = Migrate(app, root_db)


login_manager.init_app(app)
login_manager.login_view = 'signin' # Specify what page to load for NON-AUTHED users

ma.init_app(app)

app.json_encoder = JSONEncoder

CORS(app)

import models

drone_inventory/api/routes.py
from flask import Blueprint
from flask import Blueprint, request, jsonify
from helpers import token_required
from models import db,User,Drone,drone_schema,drones_schema

api = Blueprint('api',__name__, url_prefix='/api')

@api.route('/getdata')
def getdata():
    return { 'some':'value'}

@token_required
def getdata(current_user_token):
    return { 'some': 'value'}

# CREATE DRONE ENDPOINT
@api.route('/drones', methods = ['POST'])
@token_required
def create_drone(current_user_token):
    name = request.json['name']
    description = request.json['description']
    price = request.json['price']
    cam_quality = request.json['cam_quality']
    flight_time = request.json['flight_time']
    max_speed = request.json['max_speed']
    dimensions = request.json['dimensions']
    weight = request.json['weight']
    cost_of_prod = request.json['cost_of_prod']
    series = request.json['series']
    user_token = current_user_token.token

    print(f'BIG TESTER: {current_user_token.token}')

    drone = Drone(name,description,price, cam_quality,flight_time,max_speed,dimensions, weight,cost_of_prod,series,user_token = user_token )

    db.session.add(drone)
    db.session.commit()

    response = drone_schema.dump(drone)
    return jsonify(response)




# RETRIEVE ALL DRONEs ENDPOINT
@api.route('/drones', methods = ['GET'])
@token_required
def get_drones(current_user_token):
    owner = current_user_token.token
    drones = Drone.query.filter_by(user_token = owner).all()
    response = drones_schema.dump(drones)
    return jsonify(response)


# RETRIEVE ONE Drone ENDPOINT
@api.route('/drones/<id>', methods = ['GET'])
@token_required
def get_drone(current_user_token, id):
    owner = current_user_token.token
    if owner == current_user_token.token:
        drone = Drone.query.get(id)
        response = drone_schema.dump(drone)
        return jsonify(response)
    else:
        return jsonify({"message": "Valid Token Required"}),401



# UPDATE DRONE ENDPOINT
@api.route('/drones/<id>', methods = ['POST','PUT'])
@token_required
def update_drone(current_user_token,id):
    drone = Drone.query.get(id) # GET DRONE INSTANCE

    drone.name = request.json['name']
    drone.description = request.json['description']
    drone.price = request.json['price']
    drone.cam_quality = request.json['cam_quality']
    drone.flight_time = request.json['flight_time']
    drone.max_speed = request.json['max_speed']
    drone.dimensions = request.json['dimensions']
    drone.weight = request.json['weight']
    drone.cost_of_prod = request.json['cost_of_prod']
    drone.series = request.json['series']
    drone.user_token = current_user_token.token

    db.session.commit()
    response = drone_schema.dump(drone)
    return jsonify(response)


# DELETE DRONE ENDPOINT
@api.route('/drones/<id>', methods = ['DELETE'])
@token_required
def delete_drone(current_user_token, id):
    drone = Drone.query.get(id)
    db.session.delete(drone)
    db.session.commit()
    response = drone_schema.dump(drone)
    return jsonify(response) 

drone_inventory/authentication/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from forms import UserLoginForm
from models import User, db
from models import User,db, check_password_hash

from flask_login import login_user, logout_user, current_user, login_required

auth = Blueprint('auth',__name__,template_folder='auth_templates')

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    form = UserLoginForm()
    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            user = User(email, password = password)

            db.session.add(user)
            db.session.commit()

            flash(f'You have successfully created a user account {email}', 'user-created')

            return redirect(url_for('site.home'))
    except:
        raise Exception('Invalid Form Data please check your form')        
    return render_template('signup.html',form=form)

@auth.route('/signin', methods=['GET', 'POST'])
def signin():

    form = UserLoginForm()

    try:
        if request.method == 'POST' and form.validate_on_submit():
            email = form.email.data
            password = form.password.data
            print(email,password)

            logged_user = User.query.filter(User.email == email).first()
            if logged_user and check_password_hash(logged_user.password, password):
                login_user(logged_user)
                flash('You were successfully logged in: Via Email/Password', 'auth-success')
                return redirect(url_for('site.home'))
            else:
                flash('Your Email/Password is incorrect', 'auth-failed')
                return redirect(url_for('auth.signin'))
    except:
        raise Exception('Invalid Form Data: Please Check Your Form')
    return render_template('signin.html', form=form) 

drone_inventory/site/routes.py
from flask import Blueprint, render_template

"""
    some arguements are specified when creating the blueprint
    the first arguement 'site' is the blueprint name
    which is used by flask to route

    the second arg __name__ is the import name
    this is what flask uses to locate resources
"""

site = Blueprint('site',__name__,template_folder='site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

drone_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Drone Inventory API</title>
</head>
<body>

    <!-- Nav bar here -->
    <nav class='ct-nav'>
        <div>
            <img src="../static/images/Coding Drones Logo.png" alt="Coding Drones Logo">
        </div>
    

    <!-- nav items -->
        <div>
            <ul id="horizontal-list">
                <a href=""> 
                    <li>The Coding Drones Project</li>
                </a>
                <a href="">
                    <li>Donate</li>
                </a>
                <a href="{{ url_for('site.profile') }}">
                    <li>Profile</li>
                </a>
                <a href="{{ url_for('auth.signin') }}">
                    <li>Sign In</li>
                </a>
                <a href="">
                    <li>Log Out</li>
                </a>
                <a href="{{ url_for('auth.signup') }}">
                    <li>Sign Up Free</li>
                </a>
            </ul>
        </div>
    </nav> 

<!-- ending nav bar -->

{% block content %}
{% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.1/js/bootstrap.min.js"></script>
</body>
</html>

drone_inventory/templates/forms.html
<!--HTML Produced By The Flask Form-->
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <fieldset id="email-field">
            {{ form.email.label }}
            {{ form.email(class = "form-control", placeholder = "Place Email Here...")}}
        </fieldset>

        <fieldset id="pass-field">
            {{ form.password.label }}
            {{ form.password(class = "form-control", placeholder = "Place Password Here...")}}
        </fieldset>

        <!--Submit Button Area-->
        {{ form.submit_button(class = "btn btn-primary btn-block") }}
    </div>
</form>